services:
  bot:
    container_name: contour_professional_bot
    command: >
      sh -c "/app/bot > /app/log/stdout.log 2> /app/log/stderr.log"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: Asia/Yekaterinburg
      ADMIN: ${ADMIN}
      MODERATOR: ${MODERATOR}
      TELEGRAM_APITOKEN: ${TELEGRAM_APITOKEN}
    volumes:
      - /root/commercial-telegram-bot/log:/app/log
    ports:
      - 5555:6666